config/routes.rb
Rails.application.routes.draw do

  scope :wordlist do
    resources :words do
      collection do
        post :upload
        get :maintenance
        get :plot
        get :total_rank
        get :monthly_rank
        get :weekly_rank
      end
    end

    resource :session
  end
  root "words#headers"
  get "headers" => "words#headers"
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :department
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :group

  def password?(raw_password)
    BCrypt::Password.new(hashed_password) == raw_password
  end

  def password=(raw_password)
    if raw_password.kind_of?(String)
      self.hashed_password = BCrypt::Password.create(raw_password)
    elsif raw_password.nil?
      self.hashed_password = nil
    end
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  validates :name, presence: true
  validates :user, presence: true
  validates :name, uniqueness: {scope: [:user, :removed], message: "は既に登録済です"}

  scope :rank, -> {
  	select("words.user,count(*) as number")
  	.group("words.user")
  	.order("number desc")
  }

  scope :monthly_rank, -> {
  	rank.where("updated_at > ?", 1.months.ago)
  }

  scope :weekly_rank, -> {
  	rank.where("updated_at > ?", 1.weeks.ago)
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  private
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  helper_method :current_user

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to :root
    else
      @form = LoginForm.new
      render action: "new"
    end
  end

  def create
    @form = LoginForm.new(params[:login_form])

    if @form.number.present?
      user = User.find_by(number: @form.number)
    end

    if user
      session[:user_id] = user.id
      redirect_to :root
    else
      render action: "new"
    end
  end

  def show
    @user = { name: cookies.signed[:name] }
  end

  def destroy
    session.delete(:user_id)
    redirect_to :login
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  def headers
    @headers = request.headers.sort
    @ip = request.remote_ip
  end

  def maintenance
    Word.delete_all(removed: true)
    Word.find_each do |word|
      if word.name =~ /^\d+$/
        word.delete
      end
    end
    redirect_to :words
  end

  def upload
    user = cookies.signed[:name]
    file = params[:file].path.to_s
    xlsx = Roo::Excelx.new(file)

    xlsx.each_row_streaming do |row|
      name,desc,id = row.map(&:value)
      Word.create(name:name, desc:desc, user:user, removed:false)
    end
    redirect_to :words
  end

  # GET /words
  # GET /words.json
  # GET /words.xlsx
  def index
    respond_to do |format|
      format.json do
        @words = Word.where(removed: false).where("updated_at > ?",2.months.ago).order("created_at desc")
      end

      format.xlsx do
        timestamp = Time.zone.now.strftime("%Y%m%d%H%M%S")
        filename = "wordlist_#{timestamp}.xlsx"
        response.headers['Content-Disposition'] = "attachment; filename=#{filename}"
      end

      format.html{}
    end
  end

  def plot
    respond_to do |format|
      format.json do
        @plots = Word.find_by_sql('select "user",date(updated_at) as date,count(*) as count from words group by "user",date')
      end
    end
  end

  def total_rank
    respond_to do |format|
      format.json do
        @total_ranks = Word.rank
      end
    end
  end

  def monthly_rank
    respond_to do |format|
      format.json do
        @monthly_ranks = Word.monthly_rank
      end
    end
  end

  def weekly_rank
    respond_to do |format|
      format.json do
        @weekly_ranks = Word.weekly_rank
      end
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created }
      else
        format.html { render :new }
        format.json do
          render json: @word.errors.full_messages, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit }
        format.json do
          render json: @word.errors.full_messages, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:name, :desc, :user, :removed)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="jp"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title ワードリスト
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  body#app
    = yield

app/views/pages/index.html.slim
h1 ようこそ
p トップページです

app/views/pages/show.html.slim
h1 = "こんにちは#{current_user.name}さん"
p ユーザー用ページです

app/views/words/headers.html.slim
.container
  h1 接続元IPアドレス: #{@ip}
  hr
  h3 ヘッダ一覧
  table.table
    - @headers.each do |key, value|
      tr
        td
          strong = key
        td = value

app/views/words/index.html.slim
.navbar.navbar-default.navbar-static-top
  canvas#canvas width="0" height="0" style="visibility:hidden;position:absolute"
  .container
    button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
      span.icon-bar
      span.icon-bar
      span.icon-bar
    a.navbar-brand href="/"
      i class="fa fa-book"
      | ワードリスト
    .navbar-collapse.collapse.navbar-responsive-collapse
      ul.nav.navbar-nav
        li :class="{active: menu.chart}"
          a @click="setMenu('chart')"
            i class="fa fa-bar-chart"
            | グラフ

        li :class="{active: menu.rank}"
          a @click="setMenu('rank')"
            i class="fa fa-line-chart"
            | ランク

        li.dropdown :class="{active: menu.word}"
          a @click="setMenu('word')"
            i class="fa fa-files-o"
            | ワード

        li :class="{active: menu.quiz}"
          a @click="setMenu('quiz')"
            i class="fa fa-graduation-cap"
            | クイズ

        li :class="{active: menu.upload}" v-show="status.login"
          a @click="setMenu('upload')"
            i class="fa fa-upload"
            | 一括

        li v-if="status.login"
          a @click="logoff"
            i class="fa fa-user"
            = "{{user}}"

      form.navbar-form.navbar-right role="search"

        .form-group v-if="!status.login"
          input.form-control type="text" placeholder="漢字氏名" v-model="username" @keydown.enter.prevent="login"

        .form-group v-if="!status.login"
          button.btn.btn-default @click.prevent="login" ログイン

        .checkbox v-if="status.login"
          label
            input type="checkbox" v-model="checkSelf" 自分ワード

        .form-group v-if="status.login"
          select.form-control v-model="sortkey"
            option value="name" ワード順
            option value="desc" 説明順
            option value="created_at" 登録日順
            option value="updated_at" 更新日順

        .form-group v-if="status.login"
          select.form-control v-model="sortorder"
            option :value="1" 昇順
            option :value="-1" 降順

        .form-group v-if="status.login"
          input.form-control type="text" v-model="query" placeholder="検索" style="width:100px" @keydown.enter.prevent=""

.container v-if="menu.upload && status.login"
  = form_tag upload_words_path, multipart: true do
    = label_tag "ワードの一括登録（EXCEL）"
    = file_field_tag :file
    = submit_tag "登録"
  hr
    = link_to "ワードの一括ダウンロード（EXCEL）", words_path(format: "xlsx"), class: "btn btn-primary"

.container v-show="menu.chart"
  .row
    .col-xs-12
      #chart

.container v-if="menu.rank"
  .row
    .col-xs-4
      .panel.panel-default
        .panel-heading 総合ランキング
        table.table
          thead
            tr
              th 順位
              th 氏名
              th 登録ワード数
          tbody
            tr v-for="rank in totalRank"
              td v-text="$index+1"
              td v-text="rank.user"
              td v-text="rank.number"

    .col-xs-4
      .panel.panel-default
        .panel-heading 月間ランキング
        table.table
          thead
            tr
              th 順位
              th 氏名
              th 登録ワード数
          tbody
            tr v-for="rank in monthlyRank"
              td v-text="$index+1"
              td v-text="rank.user"
              td v-text="rank.number"

    .col-xs-4
      .panel.panel-default
        .panel-heading 週間ランキング
        table.table
          thead
            tr
              th 順位
              th 氏名
              th 登録ワード数
          tbody
            tr v-for="rank in weeklyRank"
              td v-text="$index+1"
              td v-text="rank.user"
              td v-text="rank.number"

.container v-if="menu.word || menu.quiz"

  .alert.alert-danger role="alert" v-if="errors.length > 0"
    button.close type="button" area-label="Close" @click="clearErrors"
      span &times;
    p v-for="error in errors" v-text="error"

  nav
    ul.pagination
      li
        a area-label="Previous" @click.prevent="toppage"
          span aria-hidden="true"
            i.fa.fa-step-backward

      li
        a area-label="Previous" @click.prevent="prevpage"
          span aria-hidden="true"
            i.fa.fa-backward

      li
        a area-label="Next" @click.prevent="nextpage"
          span area-hidden="true"
            i.fa.fa-forward

      li
        a area-label="Next" @click.prevent="lastpage"
          span area-hidden="true"
            i.fa.fa-step-forward
  br

  .item#new v-if="status.login"
    textarea.item-title{
      placeholder="ワードを入力"
      @keydown.enter.prevent="onEnter"
      v-model="name"
    }

    textarea.item-body{
      placeholder="説明を入力してエンターキーで登録"
      @keydown.enter.prevent="onEnter"
      v-model="desc"
    }

  .item v-for="word in words | filterBy query in 'name' 'desc' 'user' | filterBy filterSelf | orderBy sortkey sortorder | limitBy page.show pos" transition="item" v-show="!word.removed"


    // 編集可能カード
    template v-if="status.login && word.user == user"
      i.fa.fa-2x.fa-times.delete-button @click="remove(word)"
      textarea.item-title {
        v-model="word.name"
        :style="{fontSize: autosize(word.name)}"
        @change="update(word)"
        @keydown.enter.prevent="focusNext"
      }
      textarea.item-body {
        v-show="menu.word"
        v-model="word.desc"
        @change="update(word)"
        @keydown.enter.prevent="update(word)"
      }

    // 表示専用カード
    template v-else=""
      .item-title {
        :style="{fontSize: autosize(word.name)}"
        v-text="word.name"
      }
      .item-body {
        v-show="menu.word"
        v-text="word.desc"
      }

    .item-footer
      span v-text="word.updated_at.substr(0,10)+' '+word.updated_at.substr(11,5)"
      |&nbsp;
      span v-text="word.user"

  footer
    p &copy; Company 2016